name: Build and Run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install coverage
          pip install pandas
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-line-length=80 --ignore=E111,E121,E126 --statistics
      
      
        env:
           Solution_Name: Streamline_Sender.sln
           Test_Project_Path: Streamline_Sender_TestCase\Streamline_Sender_TestCase.csproj                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

      
            # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
          
          # Run the app
      - name: Run the App
        run: dotnet run -p Streamline_Sender 
        
      - name: Run BMS Data Streamer
        run: dotnet run --project Streamline_Sender_TestCase/Streamline_Sender_TestCase.csproj
        
        
      - name: Run test and collect coverage - Sender
        run: |
          coverage run --branch receiver/test_StreamLine_Receiver.py
          coverage html
          coverage report
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: ./htmlcov
          retention-days: 21
      - name: Run test and collect coverage - Receiver
        run: |
            coverage run --branch --source receiver -m unittest discover
            coverage html
            coverage report
      - name: Upload coverage - Receiver
        uses: actions/upload-artifact@v2
        with:
            name: coverage
            path: ./htmlcov
            retention-days: 21
