name: Sender_Coverage 

on: [push, pull_request]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: Streamline_Sender.sln
      Test_Project_Path: Streamline_Sender_TestCase\Streamline_Sender_TestCase.csproj                 # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Run tests
      run: dotnet test
      
    - name: Run the app 
      run: dotnet run -p Streamline_Sender.sln
      
    - name: Run tests and collect coverage for Sender
      run: dotnet test ./Streamline_Sender_TestCase/Streamline_Sender_TestCase.csproj   --collect:"XPlat Code Coverage"
      
    - name: Install coverage report generator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Make coverage report
      run: reportgenerator "-reports:Streamline_Sender_TestCase\TestResults\*\*.xml" "-targetdir:coverage"
    
    - name: Create coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage
        retention-days: 21
      

